spring:
  output:
    ansi:
      enabled:DETECT
  datasource:
    sql-script-encoding: UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cheetahead_fund?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: passw0rd
    tomcat:
      validation-query: SELECT 1
      test-on-borrow: true
  jpa:
    properties:
      hibernate:
        generate_statistics: false
        dialect: org.hibernate.dialect.MySQL5Dialect
        ddl-auto: none
        show_sql: true
        order_inserts: true
        order_updates: true
        connection:
          autocommit: true
        jdbc:
          fetch_size: 100
          batch_size: 50
          time_zone: Asia/Shanghai 
    generate-ddl: false
    open-in-view: false
  flyway:
    locations: classpath:db/migration
    baselineOnMigrate: true
    enabled: true
server:
  url: http://localhost:9000/
  servlet:
    contextPath: /fund
  port: 9000

  