spring:
  main:
    banner-mode: off
  output:
    ansi:
      enabled:DETECT
  datasource:
    sql-script-encoding: UTF-8
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/canglong?useSsl=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: passw0rd
  jpa:
    properties:
      hibernate:
        generate_statistics: false
        dialect: org.hibernate.dialect.MariaDB103Dialect
        ddl-auto: none
        show_sql: false
        order_inserts: true
        order_updates: true
        connection:
          autocommit: true
        jdbc:
          fetch_size: 100
          batch_size: 50
          time_zone: Asia/Shanghai 
    generate-ddl: false
    open-in-view: false
  flyway:
    locations: classpath:db/migration
    baselineOnMigrate: true
    enabled: true
server:
  url: http://localhost:9000/
  servlet:
    contextPath: /fund
  port: 9000

  