spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
    password: ${DB_PASSWORD:passw0rd}
    url: jdbc:mariadb://localhost:3306/canglong
    username: root
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
    show-sql: false
  main:
    web-application-type: servlet
fund:
  threadCount: 20
server:
  address: localhost
  servlet:
    contextPath: /fund
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  port: 9000

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when_authorized
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  show-actuator: false
  model-and-view-allowed: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  writer-with-default-pretty-printer: true