spring:
  main:
    banner-mode: off
  output:
    ansi:
      enabled:DETECT
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/canglong?useSsl=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: passw0rd
    hikari:
      minimum-idle=20
      maximum-pool-size=200
      idle-timeout=500000
      max-lifetime=540000
      connection-timeout=60000
      connection-test-query=SELECT 1
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      show_sql: true
      generate_statistics: false
      dialect: org.hibernate.dialect.MariaDB103Dialect
      order_inserts: true
      order_updates: true
    generate-ddl: false
    open-in-view: false
  flyway:
    locations: classpath:db/migration
    baselineOnMigrate: true
    enabled: true
  threadCount: 20
server:
  address: localhost
  servlet:
    contextPath: /fund
  port: 9000